[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mypackage"
version = "0.1.0"
license = {file = "LICENSE.txt"}
description = "My first package"

dependencies = [
  "numpy",
]